---
title: "時光縮影: part 2"
output: html_document
---

```{r}
xfun::download_file("https://www.dropbox.com/s/vt10xxig64levmj/list_heritageYears.json?dl=1", mode="wb")
list_heritageYears <- jsonlite::fromJSON("list_heritageYears.json")
```

## 處理非正規書寫西元年份

### 民國

```{r}
purrr::map(
  list_heritageYears,
  ~{
    stringr::str_subset(.x, "民國")
  }
) -> list_minguo
table(unlist(list_minguo))
```

### 中文西元年份

```{r}
pattern <- "一[０一二三四五六七八九十]{3}"
purrr::map(
  list_heritageYears,
  ~{
    stringr::str_subset(.x, pattern)
  }
) -> list_westernYearsInChineseWriting
table(unlist(list_westernYearsInChineseWriting))
```

### 日治時代

  * 替換成"1895-1945"

---------------------------------------------------------------------------------------

# 中文西元年份
```{r}
library(stringr)
chr_num <- c("0","0","0","1","2","3","4","5","6","7","8","9","")
names(chr_num) <- c("O","○","０","一","二","三","四","五","六","七","八","九","年")
pattern <- "一[O0○０一二三四五六七八九十]{3}"
for(ii in 1:length(list_heritageYears)){
      if(length(list_heritageYears[[ii]]!=0)){
          `中文西元` <- str_subset(list_heritageYears[[ii]],pattern)
          list_heritageYears[[ii]][str_detect(list_heritageYears[[ii]],pattern)] <-
          str_replace_all(`中文西元`,chr_num)
      }
}
```

#日治(據)時代(期)
```{r}
for(ii in 1:length(list_heritageYears)){
      if(length(list_heritageYears[[ii]]!=0)){
         pattern <- "日[治據]時[期代]"
         `日` <- str_subset(list_heritageYears[[ii]],pattern)
         list_heritageYears[[ii]][str_detect(list_heritageYears[[ii]],pattern)] <-
         str_replace_all(`日`,pattern,"1895-1945")
      }
}
```

# 民國
```{r}
chinese_num <- c("○","０","一","二","三","四","五","六","七","八","九")
chr_num <- c("0","1","2","3","4","5","6","7","8","9")
names(chr_num) <- c("０","一","二","三","四","五","六","七","八","九")
pattern <- "[0-9○０一二三四五六七八九十]+"
for(ii in 1:length(list_heritageYears)){
      if(length(list_heritageYears[[ii]]!=0)){
          # 處理特例
          list_heritageYears[[ii]][str_which(list_heritageYears[[ii]],"民國一OO年")] <-
                         c(rep("2011",length(str_which(list_heritageYears[[ii]],"民國一OO年"))))
          list_heritageYears[[ii]][str_which(list_heritageYears[[ii]],"民國元年")] <-
                         c(rep("1911",length(str_which(list_heritageYears[[ii]],"民國元年"))))
          list_heritageYears[[ii]][str_which(list_heritageYears[[ii]],"民國初年")] <-
                         c(rep("1911",length(str_which(list_heritageYears[[ii]],"民國初年"))))
          list_heritageYears[[ii]][str_which(list_heritageYears[[ii]],"民國一○一年")] <-
                         c(rep("2012",length(str_which(list_heritageYears[[ii]],"民國一○一年"))))
          list_heritageYears[[ii]][str_which(list_heritageYears[[ii]],"民國一百年")] <-
                         c(rep("2011",length(str_which(list_heritageYears[[ii]],"民國一百年"))))
          list_heritageYears[[ii]][str_which(list_heritageYears[[ii]],"民國卅七年")] <-
                         c(rep("1947",length(str_which(list_heritageYears[[ii]],"民國卅七年"))))
          
          minguo <- str_subset(list_heritageYears[[ii]],"民國")
          minguo_number <- unlist(str_extract_all(minguo,pattern))
          # 純數字
          only_number <- str_subset(minguo_number,"[0-9]+")
          list_heritageYears[[ii]][str_detect(list_heritageYears[[ii]],"民國") &
                             str_detect(list_heritageYears[[ii]],"[0-9]")] <- 
                             as.character(as.numeric(only_number)+1911)
          # 中文
          # 年份 <= 10 
          less_than_10 <- str_subset(minguo_number,"\\b[一二三四五六七八九十]\\b")
          chr_num <- c("1","2","3","4","5","6","7","8","9","10")
          names(chr_num) <- c("一","二","三","四","五","六","七","八","九","十")
          less_than_10 <- str_replace_all(less_than_10,chr_num)
          # 十開頭
          ten_in_start <- str_subset(minguo_number,"^[十][:graph:]")
          chr_num <- c("1","1","2","3","4","5","6","7","8","9")
          names(chr_num) <- c("十","一","二","三","四","五","六","七","八","九")
          ten_in_start <- str_replace_all(ten_in_start,chr_num)
          # 十結尾
          ten_in_end  <- str_subset(minguo_number,"[:graph:][０十]$")
          chr_num <- c("0","0","1","2","3","4","5","6","7","8","9")
          names(chr_num) <- c("０","十","一","二","三","四","五","六","七","八","九")
          ten_in_end <- str_replace_all(ten_in_end,chr_num)
          # 十中間
          ten_in_middle <- str_subset(minguo_number,"[:graph:][０十][:graph:]")
          chr_num <- c("","1","2","3","4","5","6","7","8","9")
          names(chr_num) <- c("十","一","二","三","四","五","六","七","八","九")
          ten_in_middle <- str_replace_all(ten_in_middle,chr_num)
          chinese_to_num <- c(ten_in_start,ten_in_middle,ten_in_end,less_than_10)
          list_heritageYears[[ii]][str_detect(list_heritageYears[[ii]],"民國") &
                                   str_detect(list_heritageYears[[ii]],pattern)] <-
                                      as.character(as.numeric(chinese_to_num)+1911)
      }      
}
```












