---
title: "data exploration"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## Time alignment

```{r}
library(dplyr)
library(econR)
googleLink_download("https://drive.google.com/file/d/1Y-MY2oGCe2RSQ99JdYyHwYyR-EjLR1Ei/view?usp=sharing")
taskdata = readRDS(. %//% "taskdata.Rds")
```

Write the following function, so that 

```{r}
taskdata$before %>%
  align_date(
    date_colname = "date",
    freq = "yearly"
  )
```

will return an outcome like 
```{r}
taskdata$after
```


```{r}
#' Align data frame date column
#'
#' @param df A data frame
#' @param date A character of colname name in df that represents date (which is a Date class)
#' @param freq A character of "daily", "monthly", "quarterly" or "yearly".
#'
#' @return
#' @export
#'
#' @examples none
align_date <- function(df, date_colname, freq="daily"){
  
}
```


## 食物類

七大類中，食物類又細分以下18子類：

穀類及其製品、肉類、肉類製品、蛋類、水產品、加工水產品、蔬菜、加工蔬菜、水果、加工水果、乳類、食用油、調味品、酒、非酒精性飲料及材料、調理食品、外食費、其他食品


```{r}
xfun::download_file("https://www.dropbox.com/s/ouurt80t6ailbif/PR0101A2Mc.csv?dl=1", mode="wb")

library(readr)
cpi <- read_csv("PR0101A2Mc.csv",
locale = locale(encoding = "CP950"),
skip = 3)

data_explore <- list(
  original = cpi
)
```

請計算這18子類誰是牽動食物物價年上漲率的最主要元兇？(結果請整理成table_foodInflation dataframe模式)

```{r}
econR::googleLink_download("https://drive.google.com/file/d/12fHfa6Kr3XnAvKw_Nk-JJ5UkWr5EYPsb/view?usp=sharing")
table_foodInflation <- readRDS(. %//% "food_inflation.Rds")
```

## 2330

  * <https://www.twse.com.tw/zh/page/trading/exchange/STOCK_DAY.html>

  * May: https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=csv&date=20210501&stockNo=2330

```{r}
library(readr)
STOCK_DAY_response_csv_date_20210501_stockNo_2330_dl_1 <- read_csv("https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=csv&date=20210501&stockNo=2330&dl=1",
locale = locale(encoding = "BIG5"), skip = 1)
```

下載2021年1月到5月的資料，計算收盤價的每日上漲率。接著計算在這5個月內，每個星期二～五的平均日上漲率。

## github link download

  * original link: <https://github.com/chao87119/109-2-app101/blob/main/weekly_progress/frank/cpi.R#L16>

  * download link: <https://raw.githubusercontent.com/chao87119/109-2-app101/main/weekly_progress/frank/cpi.R>

```{r}
xfun::download_file(download_link, output=filename, mode="wb")
file.edit(filename)
```


```{r}
#' Download a Github link (provided by the clipboard) content, saved in a file and open it.
#'
#' @return
#' @export
#'
#' @examples
githublink_download_open <- function(){
  link <- clipr::read_clip()
  
}
```

