---
title: "時光縮影: part 2"
output: html_document
---

```{r}
xfun::download_file("https://www.dropbox.com/s/vt10xxig64levmj/list_heritageYears.json?dl=1", mode="wb")
list_heritageYears <- jsonlite::fromJSON("list_heritageYears.json")
```

## 處理非正規書寫西元年份

### 民國

```{r}
purrr::map(
  list_heritageYears,
  ~{
    stringr::str_subset(.x, "民國")
  }
) -> list_minguo
table(unlist(list_minguo))
```

```{r}
.root <- rprojroot::is_rstudio_project$make_fix_file()
source(
  file.path(.root(),"R/chinese.R")
)

origin <- unlist(list_minguo)

revised <- {
  stringr::str_extract(origin, "(?<=民國)[^）\\)餘年]+") -> origin2
  stringr::str_replace(origin2, "^[拾十]","一拾") -> origin3
  stringr::str_replace_all(origin3, c("前"="-", "約"=""))
  # ○ (百)，元
}

arabics <- {
  as.numeric(revised)
}

whichIsNonArabics <- which(is.na(arabics))
non_arabics <- {
  revised[whichIsNonArabics]
}

firstDigit <- {
  stringr::str_extract(non_arabics, "[元一二三四五六七八九壹貳參肆伍陸柒捌玖]$") ->
    firstDigit
  convert_chn2arabics(firstDigit) 
}

tenth <- {
  stringr::str_extract(non_arabics,
                       "[一二三四五六七八九壹貳參肆伍陸柒捌玖](?=[十拾]|０$)") -> 
    tenth
  whichIs30 <- stringr::str_which(non_arabics,"卅")
  convert_chn2arabics(tenth) -> tenth
  tenth[whichIs30] <- "3"

}

hundredth <- {
  stringr::str_extract(non_arabics,
                     "[一二三四五六七八九壹貳參肆伍陸柒捌玖](?=[百佰O○])") -> 
    hundredth
  convert_chn2arabics(hundredth) 
}

minguo_integer <- as.integer(paste(hundredth, tenth, firstDigit, sep=""))
arabics[whichIsNonArabics] <- minguo_integer

westernYear <- 1911 + arabics

year_table <- data.frame(
  origin=origin,
  revised=arabics,
  westernYear=westernYear
)

```

### 中文西元年份

```{r}
pattern <- "一[O一二三四五六七八九十]{3}"
purrr::map(
  list_heritageYears,
  ~{
    stringr::str_subset(.x, pattern)
  }
) -> list_westernYearsInChineseWriting
table(unlist(list_westernYearsInChineseWriting))
```

```{r}
westernYears <- unlist(list_westernYearsInChineseWriting)

stringr::str_remove(westernYears, "年") -> .temp
convert_chn2arabics(.temp) -> .temp
as.integer(.temp) -> finalised
```


### 日治時代

  * 替換成"1895-1945"

