---
title: "時光縮影"
output: html_document
---

  * Goal: 依使用者選定年份區間，篩出有事蹟出現在年份區間的古蹟。

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
xfun::download_file("https://www.dropbox.com/s/2rryka3cprtgfok/heritageDataRevised.Rdata?dl=1", mode="wb")
load("heritageDataRevised.Rdata")
```

```{r}
heritage1 <- heritageData[1,]
heritage1$pastHistory
```
```{r}
stringr::str_extract_all(heritage1$pastHistory, "1[0-9]{3}")
```


```{r}
heritage25 <- heritageData[25,]
heritage25$pastHistory
stringr::str_extract_all(heritage25$pastHistory, "1[0-9]{3}")

```

```{r}
list_heritageYears <- purrr::map(
  heritageData$pastHistory,
  ~unlist(stringr::str_extract_all(.x,
          paste(
          "1[0-9]{3}",
          "一.{3}年",
          "民國.{1,3}年",
          # "[\u4E00-\u9FFF]{2}時代", 
          "一[O一二三四五六七八九]{3}",
          "日[治據]時[期代]",
          sep="|")))
)
```

年份有問題檢查用：
```{r, include=FALSE}
pick_problem <- unlist(purrr::map(
  list_heritageYears,
  ~{
    length(.x)==0
  }
))
heritageData$pastHistory[pick_problem]
```


  * 先練習得到heritage1, heritage25 pastHistory提到的年份，再去練習得到所有heritage的年份。

```{r}
list_heritageYears
```

