---
title: "時光縮影: part 3"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## Load data

```{r}
xfun::download_file("https://www.dropbox.com/s/2rryka3cprtgfok/heritageDataRevised.Rdata?dl=1", mode="wb")
xfun::download_file("https://www.dropbox.com/s/vt10xxig64levmj/list_heritageYears.json?dl=1", mode="wb")
```

## 引入模組

```{r}
library(dplyr)
library(lubridate)
.root <- rprojroot::is_rstudio_project$make_fix_file()
source(
  file.path(.root(),"R/chinese_martin.R")
)
source(
  file.path(.root(),"R/years_martin.R")
)
load("heritageDataRevised.Rdata")
list_heritageYears <- jsonlite::fromJSON("list_heritageYears.json")

```


```{r}
purrr::map(
  list_heritageYears,
  ~{
    chinese$convert2westernYears(.x)
  }
) -> list_heritageYears_converted

list_heritageYears_converted %>%
  convertListYears2YearsWithHeritageIndexName() -> 
  heritageYears_indexed

# test filter algorithm
library(lubridate)
.start = 1923
.end = NA

start_date = convert2_yyyy0101(.start)
flag_endNA = is.na(.end)
end_date = ifelse(
  flag_endNA, Inf, convert2_yyyy0101(.end)
)  

flag_covertJpnRuling <- is.japanRulingPeriod(start_date, end_date)

.end = ifelse(is.na(.end), Inf, .end)
whichFitsCriterion <- 
  which(heritageYears_indexed$NotJp_ruled_years_indexed >= .start &
      heritageYears_indexed$NotJp_ruled_years_indexed <= .end)
names(heritageYears_indexed$NotJp_ruled_years_indexed)[whichFitsCriterion] %>%
  as.integer() ->
  index_heritage
selected_caseIds <- 
  unique(
    c(
      if(flag_jpnperiod) heritageYears_indexed$JP_ruled else NULL,
      if(length(index_heritage)!=0) heritageData$caseId[index_heritage] else NULL
    ))

```

## 目標

### filter_heritage

```{r}
filter_heritage(list_heritageYears, .start=1980) -> selected_caseIds
```

### filter_heritage2

```{r}
generate_filter_heritage(list_heritageYears) -> filter_heritage2
filter_heritage2(.start=1990) -> index_selected
heritageData %>%
  filter(
    caseId %in% index_selected
  ) -> selected_heritageData
selected_heritageData$pastHistory
```

### filter_byEarliestTime

```{r}
list_heritageYears_converted %>%
  get_minYears() -> minYears
heritageYears_indexed$JP_ruled
  
```


### others

```{r}
#' 列出自何時以後存在的古蹟index
#'
#' @param list_heritageYears_converted 
#' @param since an integer of year
#'
#' @return
#' @export
#'
#' @examples
exist_since <- function(list_heritageYears_converted, since){
  
  return(index_fits)
}
#' 列出在何時之前就存在的古蹟index
#'
#' @param list_heritageYears_converted 
#' @param before an integer of year
#'
#' @return
#' @export
#'
#' @examples
exist_before <- function(list_heritageYears_converted, before){
  
  return(index_fits)
}
```
