---
title: "時光縮影: part 2"
output: html_document
---

```{r}
xfun::download_file("https://www.dropbox.com/s/vt10xxig64levmj/list_heritageYears.json?dl=1", mode="wb")
list_heritageYears <- jsonlite::fromJSON("list_heritageYears.json")
```

## 處理非正規書寫西元年份

### 前言

```{r}
library(purrr)
library(lubridate)
library(stringr)
library(glue)
.root <- rprojroot::is_rstudio_project$make_fix_file()
source(file.path(.root(),"weekly_progress/yuhong/chinese_number_transfer.R"),encoding = "UTF-8")
```


### 民國

```{r}
# "民國四十九年" 至　"民國49"

ming_pattern <- "民國[卅０一二三四五六七八九十百O○]+年"

for (x in seq_along(list_heritageYears) ){
    
    ming <- str_subset(list_heritageYears[[x]], pattern = ming_pattern)
    list_heritageYears[[x]][str_detect(list_heritageYears[[x]],pattern=ming_pattern)] <-
      chinese_number_transfer(ming)
}

# "民國49" 至 "1950"

ming_pattern21 <- "民國[0-9]{1,3}"
ming_pattern22 <- "(?<=民國)[0-9]{1,3}"

for (x in seq_along(list_heritageYears) ){
    ming_num <- unlist(str_extract_all(list_heritageYears[[x]], ming_pattern22))
    
    list_heritageYears[[x]][str_detect(list_heritageYears[[x]],pattern=ming_pattern21)] <-
      as.character(as.numeric(ming_num) + 1911)
}
```

### 中文西元年份

```{r}
xxxx_year <- "一[０O○一二三四五六七八九十]{3}"

for (x in seq_along(list_heritageYears) ){
    
    xxxx <- str_subset(list_heritageYears[[x]], pattern = xxxx_year)
    
    list_heritageYears[[x]][str_detect(list_heritageYears[[x]],pattern=xxxx_year)] <-
      chinese_number_transfer(xxxx)
}
```

### 日治時代

```{r}
jp_period <- "日[治據]時[代期]"

for (x in seq_along(list_heritageYears) ){
    
    list_heritageYears[[x]][str_detect(list_heritageYears[[x]],pattern=jp_period)] <-
      "1895-1945"
}
```

### 檢查

```{r}
# 民國

purrr::map(
  list_heritageYears,
  ~{
    stringr::str_subset(.x, "民國")
  }
) -> list_minguo
table(unlist(list_minguo))

# 中文西元年份

pattern <- "一[０O○一二三四五六七八九十]{3}"
purrr::map(
  list_heritageYears,
  ~{
    stringr::str_subset(.x, pattern)
  }
) -> list_westernYearsInChineseWriting
table(unlist(list_westernYearsInChineseWriting))
```