---
drake_cache: ".puzzle"
---

# 拼圖

  * 嘉義仁武宮

```{r makecondition}
# 下載古蹟資料
xfun::download_file("https://www.dropbox.com/s/s4mv5ebhsqanpew/heritage.Rdata?dl=1", mode="wb")
load("heritage.Rdata")
```

https://data.boch.gov.tw/old_upload/_upload/Assets_new/building/487/photo/%E5%98%89%E7%BE%A9%E4%BB%81%E6%AD%A6%E5%AE%AE.jpg

```{r imgX}
# 取得第一個古蹟的圖片網址
targetUrl <- heritageData$representImage[[1]]
targetUrlencoded <- URLencode(targetUrl)

# 讀入圖片
library(magick)
magick::image_read(targetUrlencoded) -> imgX
imgX
```
#切割圖片
```{r}
##取長寬
a<-image_info(imgX)
width <- a$width
height <- a$height


##分成四部分
right_up <-image_crop(imgX,"512X341+512+0") #右上

right_down <- image_crop(imgX,"512X341+512+341") #右下

left_up <- image_crop(imgX,"512X341") #左上

left_down <- image_crop(imgX,"512X341+0+314") #左下

NewPic <- c(left_up,left_down,right_up,right_down)
```

```{r}
#隨機打亂
num <- sample(NewPic,4,FALSE)

#黏貼
a <- image_append(num[1:2],stack=TRUE)
b <- image_append(num[3:4],stack=TRUE)
Puzzle <- image_append(c(a,b))

Puzzle
```



## Magick

 * <https://cran.r-project.org/web/packages/magick/vignettes/intro.html>
 
```{r puzzleX}
magick::image_read("https://www.dropbox.com/s/tqafdnklkem45s5/imgX.jpg?dl=1") -> puzzleX
puzzleX
```

 
Tools I use: 

  * `image_info`, `image_crop`, `image_append`
  
  * `paste0`, `sample`
